### ISSUE TITLE
关于将打包好的war包放入到Tomcat中，启动时报错。都是按照配置来的，好像是SprIng原因。

### ISSUE THREAD

**Issue by It-bin** [handuyishe/dubbo-monitor#11]
严重: Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
java.lang.NoClassDefFoundError: org/springframework/web/method/support/CompositeUriComponentsContributor
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.springframework.core.type.StandardAnnotationMetadata.getAnnotatedMethods(StandardAnnotationMetadata.java:183)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:220)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:164)
	at org.springframework.context.annotation.ConfigurationClassParser.processImport(ConfigurationClassParser.java:391)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:205)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:164)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:130)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:195)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:164)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:139)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:284)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:225)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:630)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:461)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5077)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5591)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1095)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1957)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.springframework.web.method.support.CompositeUriComponentsContributor
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1856)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1705)
	... 33 more

**Comment by It-bin** [comment]
是不是JDK的问题？我的JDK是1.8的？？

**Comment by majinkai** [comment]
是dubbox版本的问题，spring4里面没有CompositeUriComponentsContributor了，你可以改一下监控依赖的spring版本，改成dubbox相同的就可以了

**Comment by It-bin** [comment]
嗯嗯，那需要改成那个版本？如何修改？初次接触Dubbo，很感激您的回答。

**Comment by majinkai** [comment]
https://github.com/majinkai/dubbo-monitor

**Comment by It-bin** [comment]
嗯，那个关于MySql版本的，需要如何修改吗，对MongDB不太懂。。

**Comment by majinkai** [comment]
参照上面发的这个版本，改造一下就可以了，就是切换一下dubbo依赖，最好是用mongo版本，mysql数据量大了之后怕撑不住

**Comment by It-bin** [comment]
真的很抱歉，一味的打扰您，就是您说的那个切换Dubbo依赖是如何做的？怎么去修改，嗯，我先把MySql配置起来，然后研究下Mongo版的。多谢您的指教！

**Comment by It-bin** [comment]
是将<spring.version>4.1.6.RELEASE</spring.version>改成2.5.6吗？

**Comment by It-bin** [comment]
您好，您还在吗？我刚去网上查了下，4.0.0RELEASE版本有这个CompositeUriComponentsContributor。我试着该下了，但是还是报那个错，这又是什么原因，是不是还需要去除Dubbo中的Spring,我去除了还是报错？？？  参考：http://stackoverflow.com/questions/21568922/classnotfoundexception-compositeuricomponentscontributor-when-running-in-jetty

**Comment by It-bin** [comment]
嗯嗯，我使用Mongo版本成功了。。感谢您！！！！

**Comment by It-bin** [comment]
还是有点问题想请教下您，我在查看图表时，查不出来，服务器报错了：org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.data.mongodb.UncategorizedMongoDbException: { "serverUsed" : "127.0.0.1:27017" , "ok" : 0.0 , "code" : 18 , "errmsg" : "Authentication failed."}; nested exception is com.mongodb.CommandFailureException: { "serverUsed" : "127.0.0.1:27017" , "ok" : 0.0 , "code" : 18 , "errmsg" : "Authentication failed."}

**Comment by It-bin** [comment]
是我Dubbo配置的问题吗？我在使用Simple-monitor时那个图表也显示不出来，我从服务器上看chars文件夹是在jetty.directory下，还有可能是其它原因吗？。

**Comment by It-bin** [comment]
这是提示信息：Request processing failed; nested exception is org.springframework.data.mongodb.UncategorizedMongoDbException: { "serverUsed" : "127.0.0.1:27017" , "ok" : 0.0 , "code" : 18 , "errmsg" : "Authentication failed."}; nested exception is com.mongodb.CommandFailureException: { "serverUsed" : "127.0.0.1:27017" , "ok" : 0.0 , "code" : 18 , "errmsg" : "Authentication failed."}

**Comment by majinkai** [comment]
要设置mongodb的用户名密码

**Comment by It-bin** [comment]
嗯嗯，我也有这样想，但是MongDB不是很会，也就从网上下了一个，装上建好数据库跑起来了，也没有去管密码。所以配置文件中没有写MongDB的的用户名密码，Mongdb好像默认是没密码的。作者大大，你如果有时间的话，把这个版本更新下，或者说明下情况，给出另一个版本的链接。还有我有个想法，想向您建议下，如果有可能把版本优化下，能做到 把哪个服务消耗的时候最多，哪个服务调用次数最多。然后可以在图标上显示出来。我觉得这样，你的这个Dubbo monitor 就很NICE,很有用，这只是我的一点点建议。还有作者大大方便留一个能联系到你的方式吗？微博，QQ，博客之类，我觉得能在您闲的时候和您交流的话，对我的发展会有很大的促进。

**Comment by majinkai** [comment]
你可以看一下[Pinpoint](https://github.com/naver/pinpoint)，是专门用来做应用性能监控的，这样会更全面且专业，我正在这上面尝试开发一些插件

**Comment by dimmacro** [comment]
我打包部署到tomcat下，启动的时候也是这个问题。懒的改了，将spring回退到3.2.X版本就行了。

**Comment by Mrwb** [comment]
用了majinka的个人项目就没有这个问题了
