### ISSUE TITLE
bean初始化失败

### ISSUE THREAD

**Issue by phhlove** [handuyishe/dubbo-monitor#24]
现在用浏览器访问的时候，出现bean初始化失败。

[06/06/16 01:38:18:018 CST] localhost-startStop-1  WARN support.AnnotationConfigWebApplicationContext: Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'chartsController': Injection of autowired dependencies failed; nested exception is org.springframework.beans.facto
ry.BeanCreationException: Could not autowire field: private com.handu.open.dubbo.monitor.DubboMonitorService com.handu.open.dubbo.monitor.controller.ChartsController.dubboMonitorService; nested exceptio
n is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dubboMonitorService': Injection of autowired dependencies failed; nested exception is org.springframework.bea
ns.factory.BeanCreationException: Could not autowire field: private com.handu.open.dubbo.monitor.RegistryContainer com.handu.open.dubbo.monitor.DubboMonitorService.registryContainer; nested exception is
 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'registryContainer' defined in file [/home/phh/apache-tomcat-8.0.35/webapps/dubbo-monitor/WEB-INF/classes/com/hand
u/open/dubbo/monitor/RegistryContainer.class]: Initialization of bean failed; nested exception is java.lang.ExceptionInInitializerError
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1210)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4813)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5272)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1816)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.handu.open.dubbo.monitor.DubboMonitorService com.handu.open.dubbo.monitor.controller.ChartsContr
oller.dubboMonitorService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dubboMonitorService': Injection of autowired dependencies failed; n
ested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.handu.open.dubbo.monitor.RegistryContainer com.handu.open.dubbo.monitor.DubboMonitorServ
ice.registryContainer; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'registryContainer' defined in file [/home/phh/apache-tomcat-8.0.35/weba
pps/dubbo-monitor/WEB-INF/classes/com/handu/open/dubbo/monitor/RegistryContainer.class]: Initialization of bean failed; nested exception is java.lang.ExceptionInInitializerError

**Comment by jingtingzhiwu** [comment]
我的也是这个错误，群号是多少呀？
