### ISSUE TITLE
项目启动失败

### ISSUE THREAD

**Issue by BlankKelly** [handuyishe/dubbo-monitor#32]
`信息: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
log4j:WARN Continuable parsing error 32 and column 23
log4j:WARN 元素类型为 "log4j:configuration" 的内容必须匹配 "(renderer*,throwableRenderer?,appender*,plugin*,(category|logger)*,root?,(categoryFactory|loggerFactory)?)"。
log4j:WARN Continuable parsing error 32 and column 23
log4j:WARN 元素类型为 "log4j:configuration" 的内容必须匹配 "(renderer*,throwableRenderer?,appender*,plugin*,(category|logger)*,root?,(categoryFactory|loggerFactory)?)"。
[04/12/16 10:23:16:016 CST] localhost-startStop-1  INFO context.ContextLoader: Root WebApplicationContext: initialization started
[04/12/16 10:23:16:016 CST] localhost-startStop-1 ERROR context.ContextLoader: Context initialization failed
java.lang.NoClassDefFoundError: org/springframework/context/annotation/AnnotationConfigRegistry
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:3196)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:1373)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1861)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1735)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:266)
	at org.springframework.web.context.ContextLoader.determineContextClass(ContextLoader.java:466)
	at org.springframework.web.context.ContextLoader.createWebApplicationContext(ContextLoader.java:355)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:293)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5118)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5634)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1092)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1984)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.springframework.context.annotation.AnnotationConfigRegistry
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1892)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1735)
	... 25 more
十二月 04, 2016 10:23:16 上午 org.apache.catalina.core.StandardContext startInternal
严重: One or more listeners failed to start. Full details will be found in the appropriate container log file
十二月 04, 2016 10:23:16 上午 org.apache.catalina.core.StandardContext startInternal
严重: Context [/dubbo-monitor] startup failed due to previous errors
`

**Comment by ayhero** [comment]
log的配置文件有问题，貌似这都没人管理更新了吧
